### ISSUE TITLE
Could not find source label errors

### ISSUE THREAD

**Issue by asten77** [The127/MScript#23]
This code compiles successfully:

def db as base;
def d0 as GasSensor;
def d1 as WallCooler;
def d2 as WallHeater;

def $midTemp as 23;
def $lowTemp as 20;
def $highTemp as 26;

fn main (){
        var getTemp;
        var cooling;
        var heating;
        loop {
                read GasSensor.Temperature into getTemp;
                read WallCooler.On into cooling;
                read WallHeater.On into heating;
       }
}

If I add one more line, to simply, say, round the getTemp variable (or do anything else, like an if statement)
              getTemp = round(getTemp);

Then I get the following error:

Exception in thread "main" com.github.The127.MScript.MScriptCompilationException: Could not find source label: {source::goto::__round}pop r4
        at com.github.The127.MScript.LabelResolver.lambda$resolveLabels$0(LabelResolver.java:34)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at com.github.The127.MScript.LabelResolver.resolveLabels(LabelResolver.java:28)
        at com.github.The127.MScript.MScriptCompiler.main(MScriptCompiler.java:37)

I have tried renaming the variable, moving the round into a function and returning the result as in the 1 sample program provided, but always get this error.  I don't understand what Could not find source label means. 

Help is appreciated... I really like this concept a lot!

Thanks!

**Comment by asten77** [comment]
Ok, I can do this just fine.  
getTemp = 0;  
getTemp = getTemp + 1;

My best guess is GasSensor.Temperature isn't valid (although it doesn't complain on that read).  It is not clear how to enumerate what the valid list of things is.

**Comment by The127** [comment]
Hi, thanks for opening an issue and using this little project.
I could reproduce and fix the "Could not find source label: {source::goto::__round}pop r4" bug.
My latest commit should have fixed this one.

**Comment by asten77** [comment]
Thanks, I will give it a try and report back.  Cheers!

**Comment by asten77** [comment]
This worked, thank you!

I haven't done Assembly with any regularity in 20 years.  This was much nicer!
